# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pythonclient
from pythonclient.api.api_keys_api import ApiKeysApi  # noqa: E501
from pythonclient.rest import ApiException


class TestApiKeysApi(unittest.TestCase):
    """ApiKeysApi unit test stubs"""

    def setUp(self):
        self.api = pythonclient.api.api_keys_api.ApiKeysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_ap_ikey(self):
        """Test case for add_ap_ikey

        Creates an API key.  # noqa: E501
        """
        pass

    def test_delete_ap_ikey(self):
        """Test case for delete_ap_ikey

        Delete API key.  # noqa: E501
        """
        pass

    def test_get_ap_ikeys(self):
        """Test case for get_ap_ikeys

        Get auth keys.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
