# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from gpyclient.configuration import Configuration


class DashboardThresholdsConfigStepsModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'color': 'str',
        'state': 'str',
        'value': 'float'
    }

    attribute_map = {
        'color': 'color',
        'state': 'state',
        'value': 'value'
    }

    def __init__(self, color=None, state=None, value=None, _configuration=None):  # noqa: E501
        """DashboardThresholdsConfigStepsModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._color = None
        self._state = None
        self._value = None
        self.discriminator = None

        self.color = color
        if state is not None:
            self.state = state
        if value is not None:
            self.value = value

    @property
    def color(self):
        """Gets the color of this DashboardThresholdsConfigStepsModel.  # noqa: E501

        TODO docs  # noqa: E501

        :return: The color of this DashboardThresholdsConfigStepsModel.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this DashboardThresholdsConfigStepsModel.

        TODO docs  # noqa: E501

        :param color: The color of this DashboardThresholdsConfigStepsModel.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def state(self):
        """Gets the state of this DashboardThresholdsConfigStepsModel.  # noqa: E501

        TODO docs TODO are the values here enumerable into a disjunction? Some seem to be listed in typescript comment  # noqa: E501

        :return: The state of this DashboardThresholdsConfigStepsModel.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this DashboardThresholdsConfigStepsModel.

        TODO docs TODO are the values here enumerable into a disjunction? Some seem to be listed in typescript comment  # noqa: E501

        :param state: The state of this DashboardThresholdsConfigStepsModel.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def value(self):
        """Gets the value of this DashboardThresholdsConfigStepsModel.  # noqa: E501

        TODO docs FIXME the corresponding typescript field is required/non-optional, but nulls currently appear here when serializing -Infinity to JSON  # noqa: E501

        :return: The value of this DashboardThresholdsConfigStepsModel.  # noqa: E501
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DashboardThresholdsConfigStepsModel.

        TODO docs FIXME the corresponding typescript field is required/non-optional, but nulls currently appear here when serializing -Infinity to JSON  # noqa: E501

        :param value: The value of this DashboardThresholdsConfigStepsModel.  # noqa: E501
        :type: float
        """

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DashboardThresholdsConfigStepsModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DashboardThresholdsConfigStepsModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DashboardThresholdsConfigStepsModel):
            return True

        return self.to_dict() != other.to_dict()
