# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gpyclient
from gpyclient.api.signed_in_user_api import SignedInUserApi  # noqa: E501
from gpyclient.rest import ApiException


class TestSignedInUserApi(unittest.TestCase):
    """SignedInUserApi unit test stubs"""

    def setUp(self):
        self.api = gpyclient.api.signed_in_user_api.SignedInUserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_change_user_password(self):
        """Test case for change_user_password

        Change Password.  # noqa: E501
        """
        pass

    def test_clear_help_flags(self):
        """Test case for clear_help_flags

        Clear user help flag.  # noqa: E501
        """
        pass

    def test_get_signed_in_user(self):
        """Test case for get_signed_in_user

        Get signed in User.  # noqa: E501
        """
        pass

    def test_get_signed_in_user_auth_tokens(self):
        """Test case for get_signed_in_user_auth_tokens

        Auth tokens of the actual User.  # noqa: E501
        """
        pass

    def test_get_signed_in_user_org_list(self):
        """Test case for get_signed_in_user_org_list

        Organizations of the actual User.  # noqa: E501
        """
        pass

    def test_get_signed_in_user_team_list(self):
        """Test case for get_signed_in_user_team_list

        Teams that the actual User is member of.  # noqa: E501
        """
        pass

    def test_get_user_quotas(self):
        """Test case for get_user_quotas

        Fetch user quota.  # noqa: E501
        """
        pass

    def test_revoke_signed_in_auth_token_cmd(self):
        """Test case for revoke_signed_in_auth_token_cmd

        Revoke an auth token of the actual User.  # noqa: E501
        """
        pass

    def test_set_help_flag(self):
        """Test case for set_help_flag

        Set user help flag.  # noqa: E501
        """
        pass

    def test_star_dashboard(self):
        """Test case for star_dashboard

        Star a dashboard.  # noqa: E501
        """
        pass

    def test_unstar_dashboard(self):
        """Test case for unstar_dashboard

        Unstar a dashboard.  # noqa: E501
        """
        pass

    def test_update_signed_in_user(self):
        """Test case for update_signed_in_user

        Update signed in User.  # noqa: E501
        """
        pass

    def test_user_set_using_org(self):
        """Test case for user_set_using_org

        Switch user context for signed in user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
