# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gpyclient
from gpyclient.api.licensing_api import LicensingApi  # noqa: E501
from gpyclient.rest import ApiException


class TestLicensingApi(unittest.TestCase):
    """LicensingApi unit test stubs"""

    def setUp(self):
        self.api = gpyclient.api.licensing_api.LicensingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_license_token(self):
        """Test case for delete_license_token

        Remove license from database.  # noqa: E501
        """
        pass

    def test_get_custom_permissions_csv(self):
        """Test case for get_custom_permissions_csv

        Get custom permissions report in CSV format.  # noqa: E501
        """
        pass

    def test_get_custom_permissions_report(self):
        """Test case for get_custom_permissions_report

        Get custom permissions report.  # noqa: E501
        """
        pass

    def test_get_license_status(self):
        """Test case for get_license_status

        Check license availability.  # noqa: E501
        """
        pass

    def test_get_license_token(self):
        """Test case for get_license_token

        Get license token.  # noqa: E501
        """
        pass

    def test_post_license_token(self):
        """Test case for post_license_token

        Create license token.  # noqa: E501
        """
        pass

    def test_post_renew_license_token(self):
        """Test case for post_renew_license_token

        Manually force license refresh.  # noqa: E501
        """
        pass

    def test_refresh_license_stats(self):
        """Test case for refresh_license_stats

        Refresh license stats.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
