# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gpyclient
from gpyclient.api.recording_rules_api import RecordingRulesApi  # noqa: E501
from gpyclient.rest import ApiException


class TestRecordingRulesApi(unittest.TestCase):
    """RecordingRulesApi unit test stubs"""

    def setUp(self):
        self.api = gpyclient.api.recording_rules_api.RecordingRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_recording_rule(self):
        """Test case for create_recording_rule

        Create a new recording rule.  # noqa: E501
        """
        pass

    def test_create_recording_rule_write_target(self):
        """Test case for create_recording_rule_write_target

        Create a new write target.  # noqa: E501
        """
        pass

    def test_delete_recording_rule(self):
        """Test case for delete_recording_rule

        Delete a recording rule.  # noqa: E501
        """
        pass

    def test_delete_recording_rule_write_target(self):
        """Test case for delete_recording_rule_write_target

        Delete the write target.  # noqa: E501
        """
        pass

    def test_get_recording_rule_write_target(self):
        """Test case for get_recording_rule_write_target

        Get the write target.  # noqa: E501
        """
        pass

    def test_list_recording_rules(self):
        """Test case for list_recording_rules

        Get all recording rules.  # noqa: E501
        """
        pass

    def test_test_create_recording_rule(self):
        """Test case for test_create_recording_rule

        Test a recording rule.  # noqa: E501
        """
        pass

    def test_update_recording_rule(self):
        """Test case for update_recording_rule

        Update a recording rule.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
