# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gpyclient
from gpyclient.api.admin_users_api import AdminUsersApi  # noqa: E501
from gpyclient.rest import ApiException


class TestAdminUsersApi(unittest.TestCase):
    """AdminUsersApi unit test stubs"""

    def setUp(self):
        self.api = gpyclient.api.admin_users_api.AdminUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user(self):
        """Test case for create_user

        Create new user.  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete global User.  # noqa: E501
        """
        pass

    def test_disable_user(self):
        """Test case for disable_user

        Disable user.  # noqa: E501
        """
        pass

    def test_enable_user(self):
        """Test case for enable_user

        Enable user.  # noqa: E501
        """
        pass

    def test_get_auth_tokens(self):
        """Test case for get_auth_tokens

        Return a list of all auth tokens (devices) that the user currently have logged in from.  # noqa: E501
        """
        pass

    def test_get_user_quota(self):
        """Test case for get_user_quota

        Fetch user quota.  # noqa: E501
        """
        pass

    def test_logout_user(self):
        """Test case for logout_user

        Logout user revokes all auth tokens (devices) for the user. User of issued auth tokens (devices) will no longer be logged in and will be required to authenticate again upon next activity.  # noqa: E501
        """
        pass

    def test_revoke_auth_token(self):
        """Test case for revoke_auth_token

        Revoke auth token for user.  # noqa: E501
        """
        pass

    def test_set_password(self):
        """Test case for set_password

        Set password for user.  # noqa: E501
        """
        pass

    def test_set_permissions(self):
        """Test case for set_permissions

        Set permissions for user.  # noqa: E501
        """
        pass

    def test_update_user_quota(self):
        """Test case for update_user_quota

        Update user quota.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
