# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gpyclient
from gpyclient.api.teams_api import TeamsApi  # noqa: E501
from gpyclient.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = gpyclient.api.teams_api.TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_team_member(self):
        """Test case for add_team_member

        Add Team Member.  # noqa: E501
        """
        pass

    def test_create_team(self):
        """Test case for create_team

        Add Team.  # noqa: E501
        """
        pass

    def test_delete_team_by_id(self):
        """Test case for delete_team_by_id

        Delete Team By ID.  # noqa: E501
        """
        pass

    def test_get_team(self):
        """Test case for get_team

        Get Team By ID.  # noqa: E501
        """
        pass

    def test_get_team_members(self):
        """Test case for get_team_members

        Get Team Members.  # noqa: E501
        """
        pass

    def test_get_team_preferences(self):
        """Test case for get_team_preferences

        Get Team Preferences.  # noqa: E501
        """
        pass

    def test_remove_team_member(self):
        """Test case for remove_team_member

        Remove Member From Team.  # noqa: E501
        """
        pass

    def test_search_teams(self):
        """Test case for search_teams

        Team Search With Paging.  # noqa: E501
        """
        pass

    def test_update_team(self):
        """Test case for update_team

        Update Team.  # noqa: E501
        """
        pass

    def test_update_team_member(self):
        """Test case for update_team_member

        Update Team Member.  # noqa: E501
        """
        pass

    def test_update_team_preferences(self):
        """Test case for update_team_preferences

        Update Team Preferences.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
