# coding: utf-8

"""
    Grafana HTTP API.

    The Grafana backend exposes an HTTP API, the same API is used by the frontend to do everything from saving dashboards, creating users and updating data sources.  # noqa: E501

    OpenAPI spec version: 0.0.1
    Contact: hello@grafana.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import gpyclient
from gpyclient.api.admin_provisioning_api import AdminProvisioningApi  # noqa: E501
from gpyclient.rest import ApiException


class TestAdminProvisioningApi(unittest.TestCase):
    """AdminProvisioningApi unit test stubs"""

    def setUp(self):
        self.api = gpyclient.api.admin_provisioning_api.AdminProvisioningApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_reload_provisioned_access_control(self):
        """Test case for reload_provisioned_access_control

        Reload access control provisioning configurations.  # noqa: E501
        """
        pass

    def test_reload_provisioned_alert_notifiers(self):
        """Test case for reload_provisioned_alert_notifiers

        Reload legacy alert notifier provisioning configurations.  # noqa: E501
        """
        pass

    def test_reload_provisioned_dashboards(self):
        """Test case for reload_provisioned_dashboards

        Reload dashboard provisioning configurations.  # noqa: E501
        """
        pass

    def test_reload_provisioned_datasources(self):
        """Test case for reload_provisioned_datasources

        Reload datasource provisioning configurations.  # noqa: E501
        """
        pass

    def test_reload_provisioned_plugins(self):
        """Test case for reload_provisioned_plugins

        Reload plugin provisioning configurations.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
